openapi: 3.0.0
info:
  version: 1.0.0
  title: QR Docent APIs
  description: ''
  
servers:
  - url: https://qrdocent.com/api
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  
  
paths: 
  # =============================== Museum APIs ===============================
  
  /registerMuseumUser:
    post:
      tags:
        - Museum
      summary: Registers a mobile user
      description: Pass in a valid phone number in the request body following the format [+] [country code] [subscriber number including area code].
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                phoneNumber:
                  type: string
              example: 
                phoneNumber: '+13057101065'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Registration successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Registration failed
                  
  /loginMuseumUser:
    post:
      tags:
        - Museum
      summary: Logs in a mobile user
      description: Sends a confirmation code if the phone number is registered. Pass in a valid phone number in the request body following the format [+] [country code] [subscriber number including area code].
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                phoneNumber:
                  type: string
              example: 
                phoneNumber: '+13057101065'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Login successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Login failed
                  
  /verifyMuseumUserConfirmationCode:
    post:
      tags:
        - Museum
      summary: Verifies the confirmation code sent to a mobile user
      description: Pass in a valid phone number in the request body following the format [+] [country code] [subscriber number including area code].
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                phoneNumber:
                  type: string
                confirmationCode:
                  type: string
              example: 
                phoneNumber: '+13057101065'
                confirmationCode: '956143'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      accessToken: '<access token>'
                      refreshToken: '<refresh token>'
                  summary: Verification successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Verification failed
                  
  /refreshMuseumUserToken:
    get:
      tags:
        - Museum
      summary: Resfreshes a mobile users access token
      description: Once an access token has expired, use this to receive a new one. The refresh token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {refresh token}'.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      accessToken: '<access token>'
                  summary: Successfully retreive new access token
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Refresh token provided is empty or invalid
                  
  /createMuseumUserScan:
    post:
      tags:
        - Museum
      summary: Creates a scan for a mobile user
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                exhibitID:
                  type: integer
              example: 
                exhibitID: 3
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      createdScan:
                        scanID: 21
                        name: 'test exhibit'
                        description: 'description for the test exhibit'
                        mainImage: 'image.com/mainImage'
                        contents:
                          - URL: 'www.video.com/video'
                            description: 'content description'
                            position: 1
                            contentTypeID: 2
                          - URL: 'www.image.com/image'
                            description: 'content description'
                            position: 2
                            contentTypeID: 1
                  summary: Scan creation successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Scan creation failed
                  
  /deleteMuseumUserScan:
    post:
      tags:
        - Museum
      summary: Deletes a scan for a mobile user
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                scanID:
                  type: integer
              example: 
                scanID: 1
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Scan deletion successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Scan deletion failed
                  
  /getAllMuseumUserScans:
    get:
      tags:
        - Museum
      summary: Gets all scans for a mobile user
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      scans: 
                      - scanID: 21
                        name: 'test exhibit'
                        description: 'description for the test exhibit'
                        mainImage: 'image.com/mainImage1'
                        contents:
                          - URL: 'www.video.com/video'
                            description: 'content description'
                            position: 1
                            contentTypeID: 2
                          - URL: 'www.image.com/image'
                            description: 'content description'
                            position: 2
                            contentTypeID: 1
                      - scanID: 22
                        name: 'test exhibit 2'
                        description: 'description for the test second exhibit'
                        mainImage: 'image.com/mainImage2'
                        contents:
                          - URL: 'www.image.com/image'
                            description: 'content description'
                            position: 1
                            contentTypeID: 1
                          - URL: 'www.song.com/song'
                            description: 'content description'
                            position: 2
                            contentTypeID: 3
                  summary: Scans retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Scans retrieval failed
                 
                 
  # =============================== Admin APIs ===============================        
      
  /registerAdminUser:
    post:
      tags:
        - Admin
      summary: Registers an admin user
      description: An authorization code must be sent along with the credentials to register an admin.
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                museumID:
                  type: integer
                authorization:
                  type: string
              example: 
                email: 'test@email.com'
                password: 'mypass123'
                museumID: 1
                authorization: 'myAuthCode'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Registration successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Registration failed
                  
  /loginAdminUser:
    post:
      tags:
        - Admin
      summary: Logs in an admin user
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example: 
                email: 'test@email.com'
                password: 'mypass123'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      accessToken: '<access token>'
                      refreshToken: '<refresh token>'
                  summary: Login successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Login failed
                  
  /refreshAdminUserToken:
    get:
      tags:
        - Admin
      summary: Resfreshes an admin users access token
      description: Once an access token has expired, use this to receive a new one. The refresh token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {refresh token}'.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      accessToken: '<access token>'
                  summary: Successfully retreive new access token
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Refresh token provided is empty or invalid
                  
  /createMuseumExhibit:
    post:
      tags:
        - Admin
      summary: Creates an exhibit for a museum
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                mainImage:
                  type: string
                contents:
                  type: array
                  items: 
                    type: object
                    properties:
                      URL:
                        type: string
                      description:
                        type: string
                      position:
                        type: integer
                      contentTypeID:
                        type: integer
              example: 
                name: 'test exhibit name'
                description: 'this is my test exhibit bio'
                mainImage: 'image.com/mainImage'
                contents:
                  - URL: 'www.song.com/song'
                    description: 'content description'
                    position: 1
                    contentTypeID: 3
                  - URL: 'www.video.com/video'
                    description: 'content description'
                    position: 2
                    contentTypeID: 2
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result: 
                      exhibitID: 1
                  summary: Exhibit creation successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Exhibit creation failed
                  
  /updateMuseumExhibit:
    post:
      tags:
        - Admin
      summary: Updates an existing exhibit for a museum
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                exhibitID:
                  type: integer
                name:
                  type: string
                description:
                  type: string
                mainImage:
                  type: string
                contents:
                  type: array
                  items: 
                    type: object
                    properties:
                      URL:
                        type: string
                      description:
                        type: string
                      position:
                        type: integer
                      contentTypeID:
                        type: integer
              example: 
                exhibitID: 1
                name: 'updated test exhibit name'
                description: 'this is my updated test exhibit bio'
                mainImage: 'image.com/mainImage22'
                contents:
                  - URL: 'www.image.com/image'
                    description: 'content description'
                    position: 2
                    contentTypeID: 1
                  - URL: 'www.video.com/video'
                    description: 'content description'
                    position: 1
                    contentTypeID: 2
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Exhibit update successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Exhibit update failed
                  
  /deleteMuseumExhibit:
    post:
      tags:
        - Admin
      summary: Deletes an existing exhibit for a museum
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                exhibitID:
                  type: integer
              example: 
                exhibitID: 1
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                  summary: Exhibit deletion successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Exhibit deletion failed
                  
  /getAllMuseumExhibits:
    get:
      tags:
        - Admin
      summary: Retreives all exhibits for a museum
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'.
      security:
        - bearerAuth: []  
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      exhibits: 
                        - exhibitID: 1
                          name: 'My test Exhibit1'
                          description: 'this is my test exhibit bio'
                          mainImage: 'image.com/mainImage1'
                          exhibitStatusID: 1
                          createdAt: '2021-10-05T19:55:56.587Z'
                          contents:
                            - URL: 'www.image.com/image'
                              description: 'content description'
                              position: 1
                              contentTypeID: 1
                            - URL: 'www.song.com/song'
                              description: 'content description'
                              position: 2
                              contentTypeID: 3
                        - exhibitID: 2
                          name: 'My test Exhibit2'
                          description: 'this is my second test exhibit bio'
                          mainImage: 'image.com/mainImage2'
                          exhibitStatusID: 1
                          createdAt: '2021-10-05T19:58:59.587Z'
                          contents:
                            - URL: 'www.video.com/video'
                              description: 'content description'
                              position: 2
                              contentTypeID: 2
                  summary: Exhibits retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Exhibits retrieval failed
                  
  /createDailyAnalytics:
    post:
      tags:
        - Admin
      summary: Saves museum analytics for the day (Will be automated!)
      description: An authorization code must be sent to save museum analytics.
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                authorization:
                  type: string
              example: 
                authorization: 'myAuthCode'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      failures:
                        - success: false
                          message: '<error message>'
                        - success: false
                          message: '<error message>'
                  summary: Analytics creation successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Analytics creation failed
                  
  /getGraphAnalytics:
    post:
      tags:
        - Admin
      summary: Retrieves the graph analytics from a certain date range
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'. The dates must in the format yyyy-mm-dd.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                startDate:
                  type: string
                endDate:
                  type: string
              example: 
                startDate: '2021-11-06'
                endDate: '2021-11-07'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      exhibitPercentages: 
                        - exhibitID: 1
                          name: 'test'
                          mainImage: 'imaegURL.com'
                          exhibitScansPercentage: 33.333333
                        - exhibitID: 2
                          name: 'test2'
                          mainImage: 'imaegURL2.com'
                          exhibitScansPercentage: 33.333333
                        - exhibitID: 3
                          name: 'test3'
                          mainImage: 'imaegURL3.com'
                          exhibitScansPercentage: 33.333333
                      dates:
                        - date: '2021-11-07T04:00:00.000Z'
                          totalScans: "9"
                          averageUserVisit: '02:46:07.75'
                          exhibitAnalytics:
                          - exhibitID: 2
                            name: "test2"
                            mainImage: 'imaegURL2.com'
                            scans: 5
                          - exhibitID: 1
                            name: "test"
                            mainImage: 'imaegURL.com'
                            scans: 3
                          - exhibitID: 3
                            name: "test3"
                            mainImage: 'imaegURL3.com'
                            scans: 1
                        - date: '2021-11-06T04:00:00.000Z'
                          totalScans: "5"
                          averageUserVisit: '00:21:55.5'
                          exhibitAnalytics:
                          - exhibitID: 1
                            name: "test"
                            mainImage: 'imaegURL.com'
                            scans: 3
                          - exhibitID: 2
                            name: "test2"
                            mainImage: 'imaegURL2.com'
                            scans: 2
                          - exhibitID: 3
                            name: "test3"
                            mainImage: 'imaegURL3.com'
                            scans: 1
                  summary: Graph analytics retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Graph analytics retrieval failed
                  
  /getTotalScans:
    post:
      tags:
        - Admin
      summary: Retrieves the total scans from a certain date range
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'. The dates must in the format yyyy-mm-dd.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                startDate:
                  type: string
                endDate:
                  type: string
              example: 
                startDate: '2021-11-06'
                endDate: '2021-11-07'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      totalScans: 434
                  summary: Total scans retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Total scans retrieval failed
                  
  /getAverageDailyScans:
    post:
      tags:
        - Admin
      summary: Retrieves the average daily scans from a certain date range
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'. The dates must in the format yyyy-mm-dd.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                startDate:
                  type: string
                endDate:
                  type: string
              example: 
                startDate: '2021-11-06'
                endDate: '2021-11-07'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      averageDailyScans: '4.8571428571428571'
                  summary: Average daily scans retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Average daily scans retrieval failed
                  
  /getAverageUserVisit:
    post:
      tags:
        - Admin
      summary: Retrieves the average user visit time from a certain date range
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'. The dates must in the format yyyy-mm-dd.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                startDate:
                  type: string
                endDate:
                  type: string
              example: 
                startDate: '2021-11-06'
                endDate: '2021-11-07'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      averageUserVisit: '00:48:53.428571'
                  summary: Average user visit time retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: Average user visit time retrieval failed
                  
  /getMostPopularExhibit:
    post:
      tags:
        - Admin
      summary: Retrieves the most popular exhibit from a certain date range
      description: The access token must be passed in the HTTP header under the 'authorization' key in the format 'Bearer {access token}'. The dates must in the format yyyy-mm-dd.
      security:
        - bearerAuth: []  
      requestBody: 
        content:
          application/json:
            schema:       
              type: object
              properties:
                startDate:
                  type: string
                endDate:
                  type: string
              example: 
                startDate: '2021-11-06'
                endDate: '2021-11-07'
      responses:
        '200':
          description: Possible responses
          content:
            application/json:
              schema:
                type: object
              examples: 
                success:
                  value: 
                    success: true
                    result:
                      mostPopularExhibit:
                        exhibitID: 2
                        name: 'test2'
                        mainImage: 'imaegURL2.com'
                        scans: '7'
                  summary: The most popular exhibit retrieval successful
                failure:
                  value: 
                    success: false
                    message: '<error message>'
                  summary: The most popular exhibit retrieval failed